import javax.swing.JOptionPane;

public class Badgers {
public static void main(String[] args) {
String a1 = "Badger";
String b1 = "Mushroom";
String c1 = "Snake";
String l1 = a1 + ", " + a1 + ", " + a1;
String l2 = "A " + a1 + ", " + a1;
String l3 = b1 + ", " + b1;
String l4 = "Mush-" + b1;
String l5 = "A " + c1 + ", a " + c1;
String l6 = c1 + ", a " + c1;
String l7 = "Ooh, it's a " + c1;
String l8 = "It's a " + a1 + ", " + a1 + ", " + a1;
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l3);
JOptionPane.showMessageDialog(null, l2);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l3);
JOptionPane.showMessageDialog(null, l2);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l4);
JOptionPane.showMessageDialog(null, l5);
JOptionPane.showMessageDialog(null, l6);
JOptionPane.showMessageDialog(null, l7);
JOptionPane.showMessageDialog(null, l8);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l3);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l3);
JOptionPane.showMessageDialog(null, l2);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l3);
JOptionPane.showMessageDialog(null, l2);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l4);
JOptionPane.showMessageDialog(null, l2);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l1);
JOptionPane.showMessageDialog(null, l3);
}
}
